### ISSUE TITLE
请问想要图片和文字在一行内，怎么搞？

### ISSUE THREAD

**Issue by FISHAlready** [SevenSharp/Hommily-Editor#7]
我想上传个表情gif,想和文字一行，但发现不论是什么文件，都占一行，文字会另起一行，很不合理，怎么解决？

**Comment by FISHAlready** [comment]
二期，我要是一开始就穿图片，图片就会出现在第二行，第一行还是可以输入文字的，怎样做到文字和图片不要分开？

**Comment by FISHAlready** [comment]
很急，在线等，还有，要是上传的图片，我删了后再上传，就上传不上来了

**Comment by suyulin** [comment]
@FISHAlready  图片上传是可以的, 至于图片和文字同一行,目前没有实现

**Comment by FISHAlready** [comment]
@suyulin 谢谢你，我也是搞了半天，才发现不能在一行了，那就不适合了，我再想办法用其他的吧，谢谢啦
